<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="shortcut icon" href="src/favicon.ico" type="image/x-icon" />
        <title>Lottery Ticket Expected Value</title>

        <!-- Bootstrap -->
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="main.css">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>-->
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="bootstrap/js/bootstrap.min.js"></script>
        <script src="CalculateValue.js"></script>

    </head>

    <body>
    <div class="title">
        <div class="container">
            <h1>Expected Value of Your Ticket</h1>
            <p>This page will tell you, based on probability, how much a lottery ticket is actually worth.</p>
            <div class="moreInfo">
                <p id="1">This web page was inspired by the article found
                    <a href="http://www.businessinsider.com/heres-when-math-says-you-should-start-to-care-about-powerball-2013-9">here.</a>
                </p>
                <p id="finePrint">- Please note that the article is based on previous Powerball rules, however the concept is still the same.</p>
                <p id="2">If you want to know how the math works, check out the page source on
                    <a href="https://github.com/bquinn17/LotteryTicket">Github.</a>
                </p>
            </div>
        </div>
    </div>
    <div class="body">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="MMheader">
                            <img src="src/MMLogo.png" vspace="14" style='width: 50%; object-fit: contain'/>
                            <h1><a href="http://www.megamillions.com/">Mega Millions</a></h1>
                            <p id="m_jackpot">Current Estimated Jackpot: $</p>
                            <!--Option to select <p>Cash Option: $13 million</p>-->
                            <p id="m_price">Cost Per Ticket: $</p>
                            <p id="m_value">Expected Profit: $</p>
                            <div id="m_requestValue" style="display: none;"><?php
                                error_reporting(E_ERROR | E_PARSE);
                                $dom = new DOMDocument;
                                $dom -> loadHTMLFile('http://www.megamillions.com/index.html');
                                $xpath = new DomXPath($dom);
                                $value = $xpath -> query(
                                    '/html/body/article/div[2]/div[1]/div[1]/div/div[1]/div[1]/div/article/div/div[2]/div[2]');
                                $numberValue = htmlspecialchars($value -> item(0) -> textContent);
                                $value2 = $xpath -> query(
                                    '/html/body/article/div[2]/div[1]/div[1]/div/div[1]/div[1]/div/article/div/div[2]/div[3]');
                                $units = htmlspecialchars($value2 -> item(0) -> textContent);
                                echo $numberValue . ' ' . $units;
                                ?></div>
                            <script>
                                var div = document.getElementById("m_requestValue");
                                var jackpot = div.textContent;
                                calculateValue("m", jackpot, 1, 1);
                            </script>
                        </div>
                        <!--<div class="calculations">
                            <h1>Show me the math!!</h1>
                        </div>
                        <div class="MMTable">
                            <img src="src/MMWinningTable.png" style='height: 100%; width: 75%; object-fit: contain'/>
                        </div>-->
                    </div>
                    <div class="col-md-6">
                        <div class="PBheader">
                            <img src="src/PBLogo.png" style='width: 50%; object-fit: contain'/>
                            <h1><a href="https://www.powerball.com/">PowerBall</a></h1>
                            <p id="p_jackpot">Current Estimated Jackpot: $</p>
                            <!-- Option to select <p>$330.6 Million Cash Value</p> -->
                            <p id="p_price">Cost Per Ticket: $</p>
                            <!-- <p>Number of tickets you purchase-->
                            <p id="p_value">Expected Profit: $</p>
                            <div id="p_requestValue" style="display: none;"><?php
                                error_reporting(E_ERROR | E_PARSE);
                                $dom = new DOMDocument;
                                $html = file_get_contents('https://www.powerball.com');
                                //$html = file_get_contents('http://www.megamillions.com');
                                $dom -> loadHTML($html);
                                $xpath = new DomXPath($dom);
                                $value = $xpath ->
                                    //query('/html/body/article/div[2]/div[1]/div[1]/div/div[1]/div[1]/div/article/div/div[2]/div[2]');
                                    query('/html/body/div[1]/main/div/div[1]/article/div/div[1]/div/div/div[3]/div/div/div[2]/div[2]');
                                    //query('/html/body/div[1]/header/div[2]/div/div[1]/div[2]/span[2]');
                                // echo $html;
                                echo htmlspecialchars($value -> item(0) -> textContent) . "455 Million";
                                // echo htmlspecialchars($value -> item(0) -> nodeValue);
                            ?></div>
                            <script>
                                var div = document.getElementById("p_requestValue");
                                var myData = div.textContent;
                                calculateValue("p", myData, 2, 1);
                            </script>
                        </div>
                        <!--<div class="calculations">
                            <h1>Show me the math!!</h1>
                        </div>
                        <div class="MMTable">
                            <img src="src/PBWinningTable.png" style='height: 100%; width: 75%; object-fit: contain'/>
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
